### ISSUE TITLE
User can turn their car.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List
- [ ] Create a car object 
- [ ] Assign a direction property
- [ ] create a prototype method to change the direction based on the arrow key
- [ ] Listen to the 'keydown' events and rotate the image rendering based on what key is pressed.

**Comment by bhaisingh** [comment]
Issue resolved
