### ISSUE TITLE
User can start their car.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List
- [x] Add attribute to the object to store the present position by storing the x and y coordinates.
- [x] Use absolute positioning for the image
- [x] Use style.top and style.left property to keep the car aligned as it moves across the screen
- [x] change the position of the car every 16 mili second for smooth movement

**Comment by bhaisingh** [comment]
Issue Resolved
