### ISSUE TITLE
User can stop their car.

### ISSUE THREAD

**Issue by bhaisingh** [bhaisingh/driving-game#4]
## 💰 Motivation

If the user cannot stop their car, it goes off the page.

## 📐 Plan

Stop the car if the user presses space again.

## ✅ Task List
- [x] Add a boolean check to see if the car has started before executing stop logic.
- [x] Add Listener for 'keydown' events to stop the car when the spacebar is pressed
- [x] If the car reaches the edge of the page, Hide the car to portray car running out of the page

**Comment by bhaisingh** [comment]
Issue fixed. car can stop
